spring:
  datasource:
    ds1:
      jdbc-url: jdbc:mysql://127.0.0.1/springboot_project?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
    ds2:
      jdbc-url: jdbc:mysql://127.0.0.1/my_database?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用lettuce配置连接池
    lettuce:
      pool:
        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制
    password: 123456
swagger:
  enable: true
#actuator 开放所有的web Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


